config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'pdfs/show'

  resources :users
  resources :ranks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :attendance_managements do
    collection do
     get :index_2
     get :show_2
     get :show_3
    end
    member do
      get :edit_2
    end
  end

  namespace :admin do
    resources :attendance_managements, only: [:index, :show, :destroy] do
      collection do
        get :shift
        post :approve
      end
    end
    resources :details
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendance_managements
  has_many :details
  # belongs_to :department
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                    reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーを検索する
  def self.search(search)
    if search
      self.where(['name LIKE ?', "%#{search}%"])
    else
      self.all
    end
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :edit, :update, :destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page]).search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @attendance_management = @user.attendance_managements.where(attendance_date: Date.today.beginning_of_month..Date.today.end_of_month)
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "アカウントを有効化するためにメールを確認してください"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                    :password_confirmation, :admin, :employee_code, :payment)
    end

    # beforeアクション

    # ログイン済みユーザーかどうか確認
    # def logged_in_user
    #   unless logged_in?
    #     store_location
    #     flash[:danger] = "ログインしてください"
    #     redirect_to login_url
    #   end
    # end

    # 正しいユーザーかどうか確認
    # def correct_user
    #   @user = User.find(params[:id])
    #   redirect_to(root_url) unless current_user?(@user)
    # end

    # 管理者かどうか確認
    # def admin_user
    #   redirect_to(root_url) unless current_user.admin?
    # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-group">
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, "氏名" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード確認のため再入力" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <% if logged_in? %>
    <% if current_user.admin? %>
      <%= f.label :employee_code, "従業員コード" %>
      <%= f.text_field :employee_code, class: 'form-control' %>

      <%= f.label :payment, "時給(円)" %>
      <%= f.text_field :payment, class: 'form-control' %>
    <% end %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "編集", edit_user_path(user) %> | 
   <%= link_to "削除", user, method: :delete,
        data: { confirm: "削除しますか?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:url, user_path) %>
<% provide(:button_text, '更新') %>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h3 class="text-center">従業員情報の更新</h3>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>従業員一覧</h1>

      <%= will_paginate %>

      <p>従業員検索</p>
      <!-- <%#= form_with url: users_path do |f| %>
        <%#= f.label :name, '氏名' %>
        <%#= f.text_field :search %>
        <%#= f.submit "検索", name: nil %>
      <%# end %> -->
      <%= form_tag(users_path, :method => 'get' ) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索', :name => nil, class: "btn btn-secondary" %>
      <% end %>

      <ul class="users">
        <%= render @users %>
      </ul>

      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:url, signup_path) %>
<% provide(:button_text, 'アカウント作成') %>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h3 class="text-center">サインアップする</h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h3 class="text-center">従業員情報</h3>
        <p class="text-center"><%= link_to "従業員情報を編集", edit_user_path if current_user.admin? %></p>
        <table class="table">
          <tr>
            <th>従業員氏名</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>従業員コード</th>
            <td><%= @user.employee_code %></td>
          </tr>
          <tr>
            <th>部門</th>
            <td><%= @user.section %></td>
          </tr>
          <% if current_user.admin? %>
            <tr>
              <th>時給</th>
              <td><%= @user.payment %>円</td>
            </tr>
            <tr>
              <th>管理者権限</th>
              <td><%= @user.admin %></td>
            </tr>
        </table>
        <div id="att_regi">
        </div>
            <% unless @user.payment.blank? %>
            <div class="dropdown">
              <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                管理者メニュー
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to "給与明細を表示", admin_attendance_management_path(@user.id), class: "dropdown-item" %>
                <%= link_to "給与明細の追加項目を登録", new_admin_detail_path(d_id: @user.id), class: "dropdown-item" %>
                <%= link_to "給与明細の追加項目を表示", admin_detail_path, class: "dropdown-item" %>
              </div>
            </div>
            <% end %>
          <% end %>
        <p><%= @user.name %>さんの今月のシフト</p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>出勤日</th><th>出勤時間</th><th>退勤時間</th><th></th>
            </tr>
          </thead>
          <tbody>
            <% @attendance_management.each do |a| %>
            <tr>
              <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
              <td><%= a.sch_attendance.strftime('%H:%M') %></td>
              <td><%= a.sch_leaving.strftime('%H:%M') %></td>
                <% @a_flag = a.approval_flag %>
                <% unless @a_flag == true %>
                  <td>
                    <%= link_to "編集", edit_attendance_management_path(a.id), :remote => true %> |
                    <%= link_to "削除", attendance_management_path(a.id), method: :delete, data: { confirm: '削除しますか?' } %>
                  </td>
                <% else %>
                  <!-- <td>&nbsp;</td> -->
                  <% if a.attendance_date == Date.today %>
                    <td><%= link_to "勤怠登録", edit_2_attendance_management_path(a.id), :remote => true %></td>
                  <% else %>
                    <td>&nbsp;</td>
                  <% end %>
                <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      <p><%= link_to "来月のシフトを登録する", attendance_managements_path %></p>
    </div>
  </div>
</div>