config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'pdfs/show'

  resources :users
  resources :ranks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :attendance_managements do
    collection do
     get :index_2
     get :show_2
     get :show_3
    end
    member do
      get :edit_2
    end
  end

  namespace :admin do
    resources :attendance_managements, only: [:index, :show, :destroy] do
      collection do
        get :shift
        post :approve
      end
    end
    resources :details
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance_management.rb
class AttendanceManagement < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :attendance_date, presence: true, uniqueness: {scope: :user_id}
end

app/controllers/admin/attendance_managements_controller.rb
class Admin::AttendanceManagementsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_attendance_management, only: [:destroy]

  # 実績一覧
  def index
    @s_month = params[:s_month]
    @s_date = Date.today
    @name = params[:name]
    unless @s_month.blank?
      if @s_month == 'previous'
        @s_date = @s_date.prev_month
      elsif @s_month == 'next'
        @s_date = @s_date.next_month
      end
    end
    unless @name.blank?
      @user = User.where(name: @name).first
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month).where(user_id: @user.id)
      # this_month_extract.where(user_id: @user.id)
    else
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month)
      # this_month_extract
    end
  end

  # 給与明細
  def show
    @user = User.find(params[:id])
    @attendance_management = @user.attendance_managements.where(attendance_date: Date.today.beginning_of_month..Date.today.end_of_month)
    @detail = @user.details.where(registration_date: Date.today.beginning_of_month..Date.today.end_of_month)
    @detail.each do |d|
      @carfare = d.carfare
      @income_tax = d.income_tax
    end
    @total_time = 0
    @total_pay = 0
    @attendance_management.each do |a|
      working = (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60
      @total_time = @total_time.to_i + working.to_i
      @total_pay = @total_pay.to_i + a.user.payment.to_i * working.to_i
    end
    # 源泉徴収額計算
    if @total_pay.to_i <= 162500
      @tax = @total_pay.to_i * 0.05105
    elsif @total_pay.to_i.between?(162501, 275000)
      @tax = @total_pay.to_i * 0.1021 - 8296
    elsif @total_pay.to_i.between?(275001, 579166)
      @tax = @total_pay.to_i * 0.2042 - 36374
    elsif @total_pay.to_i.between?(579167, 750000)
      @tax = @total_pay.to_i * 0.23483 - 54113
    elsif @total_pay.to_i.between?(750001, 1500000)
      @tax = @total_pay.to_i * 0.33693 - 130688
    elsif @total_pay.to_i.between?(1500001, 3333333)
      @tax = @total_pay.to_i * 0.4084 - 237893
    else
      @tax = @total_pay.to_i * 0.45945 - 408061
    end
    respond_to do |format|
      format.html
      format.pdf { prawnto :prawn => {
        :page_layout => :portrait, # 縦:portrait、 横:landscape
        :page_size => 'A4',
        :left_margin => 20,
        :right_margin => 20,
        :top_margin => 20,
        :bottom_margin => 20
        } ,
      :inline => true
      }
    end
  end

  # シフト編集
  def shift
    @s_date = Date.today.next_month
    @name = params[:name]
    unless @name.blank?
      @user = User.where(name: @name).first
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month).where(user_id: @user.id)
      # this_month_extract.where(user_id: @user.id)
    else
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month)
      # this_month_extract
    end
  end

  # シフト確定
  def approve
    @approval_flag_all = params[:approval_flag_all]
    @date = Date.today.next_month
    if @approval_flag_all == "true"
      @attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month)
      @attendance_managements.update_all(approval_flag: true)
      flash[:success] = "シフトを確定しました。"
      redirect_to shift_admin_attendance_managements_path
    else
      flash[:danger] = "シフトの確定に失敗しました。"
      redirect_to shift_admin_attendance_managements_path
    end
  end

  def destroy
    @attendance_management.destroy
    flash.now[:success] = "シフトを削除しました。"
    redirect_to attendance_managements_path
  end

  private

    def set_attendance_management
      @attendance_management = AttendanceManagement.find(params[:id])
    end

    def attendance_management_params
      params.require( :attendance_management ).permit(
        :sch_attendance, :sch_leaving, :res_attendance, :res_break_in,
        :res_break_out, :res_leaving, :user_id, :attendance_date)
    end

    # def this_month_extract
    #   @attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month)
    # end
end

app/controllers/attendance_managements_controller.rb
class AttendanceManagementsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:create, :update]
  before_action :set_attendance_management, only: [:show, :edit, :edit_2, :update]
  # before_action :admin_user, only: [:shift, :approval_all, :result, :destroy]

  def index
    @date = Date.today.next_month
    attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month).where(user_id: current_user.id).order(:attendance_date)
    @h = Hash.new { |h, k| h[k] = [] }
    attendance_managements.each do |a|
      @h[a.attendance_date].push(a.id, a.sch_attendance, a.sch_leaving, a.user_id)
    end
  end

  def index_2
    @date = Date.today
  end

  def show
  end

  def show_2
    @shift_date = params[:shift_date]
    @attendance_managements = AttendanceManagement.where(attendance_date: @shift_date)
  end

  def show_3
    @shift_date = params[:shift_date]
    @attendance_managements = AttendanceManagement.where(attendance_date: @shift_date)
    respond_to do |format|
      format.html
      format.pdf { prawnto :prawn => {
        :page_layout => :landscape, # 縦:portrait、 横:landscape
        :page_size => 'A4',
        :left_margin => 20,
        :right_margin => 20,
        :top_margin => 20,
        :bottom_margin => 20
        } ,
      :inline => true
      }
    end
  end

  def new
    @attendance_management = AttendanceManagement.new
    @attendance_management.attendance_date = params[:clicked_date]
    respond_to do |format|
      format.js
    end
  end

  def create
    @attendance_management = AttendanceManagement.new(attendance_management_params)
    @attendance_management.user_id = current_user.id
    if @attendance_management.save
      flash.now[:success] = "シフトを登録しました。"
      redirect_to attendance_managements_path(current_user.id)
    else
      redirect_back(fallback_location: attendance_managements_path)
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit_2
    # respond_to do |format|
    #   format.js
    # end
  end

  def update
    if @attendance_management.update_attributes(attendance_management_params)
      flash.now[:success] = "情報を更新しました。"
      redirect_to attendance_managements_path
    else
      flash.now[:danger] = "情報の更新が出来ませんでした。"
      # redirect_to attendance_managements_path
      render :edit
    end
  end

  def destroy
    AttendanceManagement.find(params[:id]).destroy
    flash[:info] = "削除しました。"
    redirect_to attendance_managements_path(current_user.id)
  end

  private

    def set_attendance_management
      @attendance_management = AttendanceManagement.find(params[:id])
    end

    def attendance_management_params
      params.require( :attendance_management ).permit(
        :sch_attendance, :sch_leaving, :res_attendance, :res_break_in,
        :res_break_out, :res_leaving, :user_id, :attendance_date)
    end

    # def admin_user
    #   redirect_to(root_url) unless current_user.admin?
    # end
end

app/helpers/admin/attendance_managements_helper.rb
module Admin::AttendanceManagementsHelper
end

app/helpers/attendance_managements_helper.rb
module AttendanceManagementsHelper
end

app/views/attendance_managements/_edit.html.erb
<%= form_with model: @attendance_management do |f| %>
<div class="form-group">

  <%= f.label :attendance_date, "出勤日" %>
  <%= f.date_field :attendance_date,
        value: @attendance_management.attendance_date, readonly: true, class: 'form-control' %>

  <%= f.label :sch_attendance, "出勤時間" %>
  <%= f.time_field :sch_attendance, class: 'form-control' %>

  <%= f.label :sch_leaving, "退勤時間" %>
  <%= f.time_field :sch_leaving, class: 'form-control' %>

  <%= f.submit '編集', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/attendance_managements/_edit_2.html.erb
<%= form_for @attendance_management do |f| %>
<div class="form-group">
  <%= f.label :res_attendance, "出勤時間" %>
  <%= f.time_field :res_attendance,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_break_in, "休憩開始" %>
  <%= f.time_field :res_break_in,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_break_out, "休憩終了" %>
  <%= f.time_field :res_break_out,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_leaving, "退勤時間" %>
  <%= f.time_field :res_leaving,
        value: Time.now, class: 'form-control' %>

  <%= f.submit '登録', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/attendance_managements/_new.html.erb
<%= form_for @attendance_management do |f| %>
<div class="form-group">
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :attendance_date, "出勤日" %>
  <%= f.date_field :attendance_date,
        value: @attendance_management.attendance_date, class: 'form-control', readonly: true %>

  <%= f.label :sch_attendance, "出勤時間" %>
  <%= f.time_field :sch_attendance, class: 'form-control' %>

  <%= f.label :sch_leaving, "退勤時間" %>
  <%= f.time_field :sch_leaving, class: 'form-control' %>

  <%= f.submit '登録', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/attendance_managements/attendance.html.erb
<%= form_for @attendance_management do |f| %>
<div class="form-group">
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :attendance_date, "出勤日" %>
  <%= f.date_field :attendance_date,
        value: @attendance_management.attendance_date, class: 'form-control' %>

  <%= f.label :res_attendance, "出勤時間" %>
  <%= f.time_field :sch_attendance, value: Time.now, class: 'form-control' %>

  <%= f.label :res_leaving, "退勤時間" %>
  <%= f.time_field :sch_leaving, value: Time.now, class: 'form-control' %>

  <%= f.submit '登録', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/attendance_managements/edit.js.erb
$('.input-form').html("<%= j (render 'edit') %>");

app/views/attendance_managements/edit_2.html.erb
<%= form_for @attendance_management do |f| %>
<div class="form-group">
  <%= f.label :res_attendance, "出勤時間" %>
  <%= f.time_field :res_attendance,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_break_in, "休憩開始" %>
  <%= f.time_field :res_break_in,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_break_out, "休憩終了" %>
  <%= f.time_field :res_break_out,
        value: Time.now, class: 'form-control' %>

  <%= f.label :res_leaving, "退勤時間" %>
  <%= f.time_field :res_leaving,
        value: Time.now, class: 'form-control' %>

  <%= f.submit '登録', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/attendance_managements/edit_2.js.erb
$('#att_regi').html("<%= j (render 'edit_2') %>");

app/views/attendance_managements/index.html.erb
<div class="container">
  <h1><%= current_user.name %>さんのシフトの登録</h1>
  <div>
    <div>
      <table class="table table-bordered">
        <h3><%= @date.strftime('%Y年%m月') %></h3>
        <thead>
          <tr>
            <th>日</th>
            <th>月</th>
            <th>火</th>
            <th>水</th>
            <th>木</th>
            <th>金</th>
            <th>土</th>
          </tr>
        </thead>
        <tbody>
        <% month = @date.strftime('%m') %>
        <% d = @date.at_beginning_of_month.at_beginning_of_week(:sunday) %>
        <% 1.upto(6).each do |i| %>
          <tr>
            <% (d..d.end_of_week(:sunday)).each do |c| %>
              <td>
                <%= link_to new_attendance_management_path(clicked_date: c, id: current_user.id),
                                                              :remote => true do %>
                  <%= c.strftime('%m') == month ? c.strftime('%d') : "" %>
                <% end %>
                <!-- <%# binding.pry %> -->
                  <% if @h.has_key?(c) %>
                    <% if current_user.id == @h[c][3] %>
                    <!-- <%# binding.pry %> -->
                      <%= link_to edit_attendance_management_path(@h[c][0]), :remote => true do %>
                        <svg class="bi bi-pencil-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path d="M15.502 1.94a.5.5 0 010 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 01.707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 00-.121.196l-.805 2.414a.25.25 0 00.316.316l2.414-.805a.5.5 0 00.196-.12l6.813-6.814z"/>
                          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 002.5 15h11a1.5 1.5 0 001.5-1.5v-6a.5.5 0 00-1 0v6a.5.5 0 01-.5.5h-11a.5.5 0 01-.5-.5v-11a.5.5 0 01.5-.5H9a.5.5 0 000-1H2.5A1.5 1.5 0 001 2.5v11z" clip-rule="evenodd"/>
                        </svg><span> 編集</span>
                      <% end %>
                      <%= link_to attendance_management_path(@h[c][0]), method: :delete, data: { confirm: '削除しますか?' } do %>
                        <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                          <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                        </svg><span> 削除</span>
                      <% end %><br>
                      <%= @h[c][1].strftime('%H:%M 出勤') %><br>
                      <%= @h[c][2].strftime('%H:%M 退勤') %>
                    <% end %>
                  <% end %>
              </td>
            <% end %>
          </tr>
          <% d = d + 1.week %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="input-form"></div>
</div>

app/views/attendance_managements/index_2.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col">
      <h3 class="text-center">シフト表</h3>
      <h4><%= @date.strftime('%Y年%m月') %></h4>
      <table class="table table-bordered text-center">
        <thead class="thead-light">
          <tr>
            <th>日</th>
            <th>月</th>
            <th>火</th>
            <th>水</th>
            <th>木</th>
            <th>金</th>
            <th>土</th>
          </tr>
        </thead>
        <tbody>
        <% month = @date.strftime('%m') %>
        <% d = @date.at_beginning_of_month.at_beginning_of_week(:sunday) %>
        <% 1.upto(6).each do |i| %>
          <tr>
            <% (d..d.end_of_week(:sunday)).each do |c| %>
              <td>
                <%= link_to show_2_attendance_managements_path(shift_date: c) do %>
                  <%= c.strftime('%m') == month ? c.strftime('%d') : "" %>
                <% end %>
              </td>
            <% end %>
          </tr>
          <% d = d + 1.week %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/attendance_managements/new.js.erb
$('.input-form').html("<%= j (render 'new') %>");

app/views/attendance_managements/result.html.erb
<div class="container">
  <h3>勤怠実績一覧</h3>
  <div>
    <span>
      <%= link_to "前月", result_attendance_managements_path(s_month: 'previous'), method: :post %>
    </span> |
    <span>
      <%= link_to "翌月", result_attendance_managements_path(s_month: 'next'), method: :post %>
    </span>
    <span>
      <%= form_with url: result_attendance_managements_path, method: :post, local: true do |f| %>
        <%= f.label :name, '氏名で検索する' %>
        <%= f.text_field :name %>

        <!-- <%#= f.select :s_month, [['先月', 1], ['先々月', 2], ['三ヶ月前', 3]] %> -->

        <%= f.submit "検索", class: "btn btn-secondary" %>
      <% end %>
    </span>
  </div>
  <div class="input-form">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>氏名</th><th>出勤日</th><th>出勤時間</th><th>休憩入</th><th>休憩戻</th><th>退勤時間</th><th>労働時間(時間)</th>
        </tr>
      </thead>
      <% total = 0 %>
      <tbody>
        <% @attendance_managements.each do |a| %>
        <tr>
          <td><%= a.user.name %></td>
          <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
          <td><%= a.res_attendance.strftime('%H:%M') %></td>
          <td><%= a.res_break_in.strftime('%H:%M') %></td>
          <td><%= a.res_break_out.strftime('%H:%M') %></td>
          <td><%= a.res_leaving.strftime('%H:%M') %></td>
          <td><%= (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60 %></td>
          <% total += (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60 %>
        </tr>
        <% end %>
        <tr>
          <td colspan="6">合計</td>
          <td><%= total %></td>
        </tr>
      </tbody>
    </table>

app/views/attendance_managements/shift.html.erb
<div class="container">
  <h3>シフトの編集</h3>
  <div>
    <span>
      <%= form_with url: shift_attendance_managements_path, method: :post, local: true do |f| %>
        <%= f.label :name, '氏名で検索する' %>
        <%= f.text_field :name %>
        <%= f.submit "検索", class: "btn btn-secondary" %>
      <% end %>
    </span>
  </div>
  <div class="input-form">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>氏名</th><th>出勤日</th><th>出勤時間</th><th>退勤時間</th><th></th>
        </tr>
      </thead>
      <tbody>
        <% @attendance_managements.each do |a| %>
        <tr>
          <td><%= a.user.name %></td>
          <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
          <td><%= a.sch_attendance.strftime('%H:%M') %></td>
          <td><%= a.sch_leaving.strftime('%H:%M') %></td>
            <% @a_flag = a.approval_flag %>
            <% unless @a_flag == true %>
              <td>
                <%= link_to "編集", edit_attendance_management_path(a.id), :remote => true %> |
                <%= link_to "削除", attendance_management_path(a.id), method: :delete, data: { confirm: '削除しますか?' } %>
              </td>
            <% else %>
              <td>&nbsp;</td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <% unless @a_flag == true %>
        <%= button_to "シフトを確定する", approval_all_attendance_managements_path(approval_flag_all: true), method: :post, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendance_managements/show.html.erb
show

app/views/attendance_managements/show_2.html.erb
<div class="container mt-3">
  <h3><%= @shift_date.to_date.strftime("%Y年%m月%d日") %>のシフト</h3>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
      <tr>
        <th>氏名</th>
        <th>出勤</th>
        <th>退勤</th>
      </tr>
    </thead>
    <tbody>
      <% @attendance_managements.each do |a| %>
      <tr>
        <td><%= a.user.name %></td>
        <td><%= a.sch_attendance.strftime('%H:%M') %></td>
        <td><%= a.sch_leaving.strftime('%H:%M') %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<p><%= link_to "グラフ印刷", show_3_attendance_managements_path(shift_date: @shift_date, format: 'pdf') %></p>
<button id="mybutton" type="button" class="btn btn-primary mb-3">グラフ表示</button>
</div>
<div class="container" id="mygraph" style="height: 1000px;"></div>
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  $(function() {
    $('#mybutton').click(function(e) {

      google.charts.load("current", {packages:["timeline"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var container = document.getElementById('mygraph');
        var chart = new google.visualization.Timeline(container);
        var dataTable = new google.visualization.DataTable();
        dataTable.addColumn({ type: 'string', id: 'Name' });
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });

        var table = $("table tbody");
        table.find('tr').each(function (key, val){
          var $tds = $(this).find('td'),
              name = $tds.eq(0).text(),
              strstart = $tds.eq(1).text(),
              strend = $tds.eq(2).text(),

              st = strstart.split(':');
              ed = strend.split(':');

              dataTable.addRows([
                [ name, new Date(0,0,0,st[0],st[1]), new Date(0,0,0,ed[0],ed[1]) ]]);
        });

        var options = {
          timeline: { singleColor: '#b0c4de' }
        };

        chart.draw(dataTable, options);
      }
    });
  });
</script>