config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'pdfs/show'

  resources :users
  resources :ranks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :attendance_managements do
    collection do
     get :index_2
     get :show_2
     get :show_3
    end
    member do
      get :edit_2
    end
  end

  namespace :admin do
    resources :attendance_managements, only: [:index, :show, :destroy] do
      collection do
        get :shift
        post :approve
      end
    end
    resources :details
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance_management.rb
class AttendanceManagement < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :attendance_date, presence: true, uniqueness: {scope: :user_id}
end

app/controllers/admin/attendance_managements_controller.rb
class Admin::AttendanceManagementsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_attendance_management, only: [:destroy]

  # 実績一覧
  def index
    @s_month = params[:s_month]
    @s_date = Date.today
    @name = params[:name]
    unless @s_month.blank?
      if @s_month == 'previous'
        @s_date = @s_date.prev_month
      elsif @s_month == 'next'
        @s_date = @s_date.next_month
      end
    end
    unless @name.blank?
      @user = User.where(name: @name).first
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month).where(user_id: @user.id)
      # this_month_extract.where(user_id: @user.id)
    else
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month)
      # this_month_extract
    end
  end

  # 給与明細
  def show
    @user = User.find(params[:id])
    @attendance_management = @user.attendance_managements.where(attendance_date: Date.today.beginning_of_month..Date.today.end_of_month)
    @detail = @user.details.where(registration_date: Date.today.beginning_of_month..Date.today.end_of_month)
    @detail.each do |d|
      @carfare = d.carfare
      @income_tax = d.income_tax
    end
    @total_time = 0
    @total_pay = 0
    @attendance_management.each do |a|
      working = (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60
      @total_time = @total_time.to_i + working.to_i
      @total_pay = @total_pay.to_i + a.user.payment.to_i * working.to_i
    end
    # 源泉徴収額計算
    if @total_pay.to_i <= 162500
      @tax = @total_pay.to_i * 0.05105
    elsif @total_pay.to_i.between?(162501, 275000)
      @tax = @total_pay.to_i * 0.1021 - 8296
    elsif @total_pay.to_i.between?(275001, 579166)
      @tax = @total_pay.to_i * 0.2042 - 36374
    elsif @total_pay.to_i.between?(579167, 750000)
      @tax = @total_pay.to_i * 0.23483 - 54113
    elsif @total_pay.to_i.between?(750001, 1500000)
      @tax = @total_pay.to_i * 0.33693 - 130688
    elsif @total_pay.to_i.between?(1500001, 3333333)
      @tax = @total_pay.to_i * 0.4084 - 237893
    else
      @tax = @total_pay.to_i * 0.45945 - 408061
    end
    respond_to do |format|
      format.html
      format.pdf { prawnto :prawn => {
        :page_layout => :portrait, # 縦:portrait、 横:landscape
        :page_size => 'A4',
        :left_margin => 20,
        :right_margin => 20,
        :top_margin => 20,
        :bottom_margin => 20
        } ,
      :inline => true
      }
    end
  end

  # シフト編集
  def shift
    @s_date = Date.today.next_month
    @name = params[:name]
    unless @name.blank?
      @user = User.where(name: @name).first
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month).where(user_id: @user.id)
      # this_month_extract.where(user_id: @user.id)
    else
      @attendance_managements = AttendanceManagement.where(attendance_date: @s_date.beginning_of_month..@s_date.end_of_month)
      # this_month_extract
    end
  end

  # シフト確定
  def approve
    @approval_flag_all = params[:approval_flag_all]
    @date = Date.today.next_month
    if @approval_flag_all == "true"
      @attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month)
      @attendance_managements.update_all(approval_flag: true)
      flash[:success] = "シフトを確定しました。"
      redirect_to shift_admin_attendance_managements_path
    else
      flash[:danger] = "シフトの確定に失敗しました。"
      redirect_to shift_admin_attendance_managements_path
    end
  end

  def destroy
    @attendance_management.destroy
    flash.now[:success] = "シフトを削除しました。"
    redirect_to attendance_managements_path
  end

  private

    def set_attendance_management
      @attendance_management = AttendanceManagement.find(params[:id])
    end

    def attendance_management_params
      params.require( :attendance_management ).permit(
        :sch_attendance, :sch_leaving, :res_attendance, :res_break_in,
        :res_break_out, :res_leaving, :user_id, :attendance_date)
    end

    # def this_month_extract
    #   @attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month)
    # end
end

app/controllers/attendance_managements_controller.rb
class AttendanceManagementsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:create, :update]
  before_action :set_attendance_management, only: [:show, :edit, :edit_2, :update]
  # before_action :admin_user, only: [:shift, :approval_all, :result, :destroy]

  def index
    @date = Date.today.next_month
    attendance_managements = AttendanceManagement.where(attendance_date: @date.beginning_of_month..@date.end_of_month).where(user_id: current_user.id).order(:attendance_date)
    @h = Hash.new { |h, k| h[k] = [] }
    attendance_managements.each do |a|
      @h[a.attendance_date].push(a.id, a.sch_attendance, a.sch_leaving, a.user_id)
    end
  end

  def index_2
    @date = Date.today
  end

  def show
  end

  def show_2
    @shift_date = params[:shift_date]
    @attendance_managements = AttendanceManagement.where(attendance_date: @shift_date)
  end

  def show_3
    @shift_date = params[:shift_date]
    @attendance_managements = AttendanceManagement.where(attendance_date: @shift_date)
    respond_to do |format|
      format.html
      format.pdf { prawnto :prawn => {
        :page_layout => :landscape, # 縦:portrait、 横:landscape
        :page_size => 'A4',
        :left_margin => 20,
        :right_margin => 20,
        :top_margin => 20,
        :bottom_margin => 20
        } ,
      :inline => true
      }
    end
  end

  def new
    @attendance_management = AttendanceManagement.new
    @attendance_management.attendance_date = params[:clicked_date]
    respond_to do |format|
      format.js
    end
  end

  def create
    @attendance_management = AttendanceManagement.new(attendance_management_params)
    @attendance_management.user_id = current_user.id
    if @attendance_management.save
      flash.now[:success] = "シフトを登録しました。"
      redirect_to attendance_managements_path(current_user.id)
    else
      redirect_back(fallback_location: attendance_managements_path)
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit_2
    # respond_to do |format|
    #   format.js
    # end
  end

  def update
    if @attendance_management.update_attributes(attendance_management_params)
      flash.now[:success] = "情報を更新しました。"
      redirect_to attendance_managements_path
    else
      flash.now[:danger] = "情報の更新が出来ませんでした。"
      # redirect_to attendance_managements_path
      render :edit
    end
  end

  def destroy
    AttendanceManagement.find(params[:id]).destroy
    flash[:info] = "削除しました。"
    redirect_to attendance_managements_path(current_user.id)
  end

  private

    def set_attendance_management
      @attendance_management = AttendanceManagement.find(params[:id])
    end

    def attendance_management_params
      params.require( :attendance_management ).permit(
        :sch_attendance, :sch_leaving, :res_attendance, :res_break_in,
        :res_break_out, :res_leaving, :user_id, :attendance_date)
    end

    # def admin_user
    #   redirect_to(root_url) unless current_user.admin?
    # end
end

app/helpers/admin/attendance_managements_helper.rb
module Admin::AttendanceManagementsHelper
end

app/helpers/attendance_managements_helper.rb
module AttendanceManagementsHelper
end

app/views/admin/attendance_managements/details.html.erb
<%= link_to "#{@user.name}:PDF表示", details_admin_attendance_management_path(format: 'pdf') %>
<div>
  <p>給与明細書</p>
  <p><%= @attendance_management.first.attendance_date.strftime("%Y年%m月") %>分</p>
</div>
<div>
  <table class="table table-bordered">
    <tr>
      <th class="details-title">部門</th><th class="details-title">従業員コード</th><th class="text-center">時給</th><th class="details-title">氏名</th>
    </tr>
    <tr>
      <td class="text-center"><%= @user.section %></td>
      <td class="text-right"><%= @user.employee_code %></td>
      <td class="text-right"><%= @user.payment %></td>
      <td class="text-center"><%= @user.name %></td>
    </tr>
  </table>
</div>
<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th rowspan="2" class="text-center">勤怠</th><th class="text-center">出勤日数</th><th class="text-center">勤務時間</th><th></th><th></th>
      </tr>
      <tr>
        <td class="text-right"><%= @attendance_management.count %></td><td class="text-right"><%= @total_time %></td><td></td><td></td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th rowspan="2" class="text-center">支給</th><th class="text-center">基本給</th><th class="text-center">特別手当</th><th class="text-center">交通費</th><th></th><th></th><th></th><th></th><th></th>
        <th class="text-center">課税支給額</th><th class="text-center">非課税支給額</th><th class="text-center">総支給額</th>
      </tr>
      <tr>
        <td class="text-right"><%= @total_pay %></td><td></td><td></td><td></td><td></td><td></td><d></td><td></td><td></td><td></td><td></td><td></td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th rowspan="4" class="text-center">控除</th><th class="text-center">所得税</th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>
      </tr>
      <tr>
        <td></td><td></td><td></td><td></td><td></td><td></td><d></td><td></td><td></td><td></td><td></td><td></td>
      </tr>
      <tr>
        <th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>
      </tr>
      <tr>
        <td></td><td></td><td></td><td></td><td></td><td></td><d></td><td></td><td></td><td></td><td></td><td></td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center">差引支給額</th>
      </tr>
      <tr>
        <td></td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<%= link_to "#{@user.name}:PDF表示", details_admin_attendance_management_path(format: 'pdf') %>

app/views/admin/attendance_managements/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col">
      <h3 class="text-center">勤怠実績一覧</h3>
      <div class="btn-group" role="group" aria-label="Basic example">
        <%= button_to "前月", admin_attendance_managements_path(s_month: 'previous'), method: :get, class: "btn btn-outline-primary" %>
        <%= button_to "翌月", admin_attendance_managements_path(s_month: 'next'), method: :get, class: "btn btn-outline-primary" %>
      </div>
      <div>
        <%= form_with url: admin_attendance_managements_path, method: :get, local: true do |f| %>
          <%= f.label :name, '氏名で検索する' %>
          <%= f.text_field :name %>
          <%= f.submit "検索", class: "btn btn-secondary" %>
        <% end %>
      </div>
      <div>
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th>氏名</th><th>出勤日</th><th>出勤時間</th><th>休憩入</th><th>休憩戻</th><th>退勤時間</th><th>労働時間(時間)</th><th>時給(円)</th><th>支給額(円)</th>
            </tr>
          </thead>
          <% total_time = 0 %>
          <% total_pay = 0 %>
          <tbody>
            <% @attendance_managements.each do |a| %>
            <tr>
              <td><%= a.user.name %></td>
              <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
              <td><%= a.res_attendance.strftime('%H:%M') %></td>
              <td><%= a.res_break_in.strftime('%H:%M') %></td>
              <td><%= a.res_break_out.strftime('%H:%M') %></td>
              <td><%= a.res_leaving.strftime('%H:%M') %></td>
              <% working = (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60 %>
              <td class="text-right"><%= working %></td>
              <td class="text-right"><%= number_with_delimiter(a.user.payment) %></td>
              <td class="text-right"><%= number_with_delimiter(a.user.payment.to_i * working.to_i) %></td>
              <% total_time = total_time.to_i + working.to_i %>
              <% total_pay = total_pay.to_i + a.user.payment.to_i * working.to_i %>
            </tr>
            <% end %>
            <tr>
              <td class="text-center" colspan="6">労働時間合計 / 支給額合計(円)</td>
              <td class="text-right"><%= total_time %></td>
              <td colspan="2" class="text-right"><%= number_with_delimiter(total_pay) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/attendance_managements/result.html.erb
<div class="container">
  <h3>勤怠実績一覧</h3>
  <div>
    <span>
      <%= link_to "前月", result_admin_attendance_managements_path(s_month: 'previous'), method: :post %>
    </span> |
    <span>
      <%= link_to "翌月", result_admin_attendance_managements_path(s_month: 'next'), method: :post %>
    </span>
    <span>
      <%= form_with url: result_admin_attendance_managements_path, method: :post, local: true do |f| %>
        <%= f.label :name, '氏名で検索する' %>
        <%= f.text_field :name %>

        <!-- <%#= f.select :s_month, [['先月', 1], ['先々月', 2], ['三ヶ月前', 3]] %> -->

        <%= f.submit "検索", class: "btn btn-secondary" %>
      <% end %>
    </span>
  </div>
  <div class="input-form">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>氏名</th><th>出勤日</th><th>出勤時間</th><th>休憩入</th><th>休憩戻</th><th>退勤時間</th><th>労働時間(時間)</th><th>時給(円)</th><th>支給額(円)</th>
        </tr>
      </thead>
      <% total_time = 0 %>
      <% total_pay = 0 %>
      <tbody>
        <% @attendance_managements.each do |a| %>
        <tr>
          <td><%= a.user.name %></td>
          <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
          <td><%= a.res_attendance.strftime('%H:%M') %></td>
          <td><%= a.res_break_in.strftime('%H:%M') %></td>
          <td><%= a.res_break_out.strftime('%H:%M') %></td>
          <td><%= a.res_leaving.strftime('%H:%M') %></td>
          <% working = (a.res_leaving - a.res_attendance - (a.res_break_out - a.res_break_in)) / 60 / 60 %>
          <td><%= working %></td>
          <td><%= a.user.payment %></td>
          <td><%= a.user.payment.to_i * working.to_i %></td>
          <% total_time = total_time.to_i + working.to_i %>
          <% total_pay = total_pay.to_i + a.user.payment.to_i * working.to_i %>
        </tr>
        <% end %>
        <tr>
          <td class="result-total" colspan="6">労働時間合計 / 支給額合計(円)</td>
          <td><%= total_time %></td><td><%= total_pay %></td>
        </tr>
      </tbody>
    </table>

app/views/admin/attendance_managements/shift.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col">
      <h3>シフトの編集</h3>
      <div>
        <%= form_with url: shift_admin_attendance_managements_path, method: :get, local: true do |f| %>
          <%= f.label :name, '氏名で検索する' %>
          <%= f.text_field :name %>
          <%= f.submit "検索", class: "btn btn-secondary" %>
        <% end %>
      </div>
      <div class="input-form">
      </div>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <tr>
            <th>氏名</th><th>出勤日</th><th>出勤時間</th><th>退勤時間</th><th></th>
          </tr>
        </thead>
        <tbody>
          <% @attendance_managements.each do |a| %>
          <tr>
            <td><%= a.user.name %></td>
            <td><%= a.attendance_date.strftime("%Y年%m月%d日") %></td>
            <td><%= a.sch_attendance.strftime('%H:%M') %></td>
            <td><%= a.sch_leaving.strftime('%H:%M') %></td>
              <% @a_flag = a.approval_flag %>
              <% unless @a_flag == true %>
                <td>
                  <%= link_to "編集", edit_attendance_management_path(a.id), :remote => true %> |
                  <%= link_to "削除", attendance_management_path(a.id), method: :delete, data: { confirm: '削除しますか?' } %>
                </td>
              <% else %>
                <td>&nbsp;</td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <% unless @a_flag == true %>
          <%= button_to "シフトを確定する", approve_admin_attendance_managements_path(approval_flag_all: true), method: :post, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/attendance_managements/show.html.erb
<div class="container mt-3">
  <%= link_to "#{@user.name}:PDF表示", admin_attendance_management_path(format: 'pdf') %>
  <div>
    <strong class="text-center">給与明細書</strong>
    <p><%= @attendance_management.first.attendance_date.strftime("%Y年%m月分") %></p>
  </div>
  <div>
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th class="text-center">部門</th>
          <th class="text-center">従業員コード</th>
          <th class="text-center">時給</th>
          <th class="text-center">氏名</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-center"><%= @user.section %></td>
          <td class="text-right"><%= @user.employee_code %></td>
          <td class="text-right"><%= number_with_delimiter(@user.payment) %></td>
          <td class="text-center"><%= @user.name %></td>
        </tr>
      </tbody>
      <thead class="thead-light">
        <tr>
          <th rowspan="2" class="text-center">勤怠</th>
          <th class="text-center">出勤日数</th>
          <th class="text-center">勤務時間</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td class="text-right"><%= @attendance_management.count %></td>
          <td class="text-right"><%= @total_time %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
      <thead class="thead-light">
        <tr>
          <th rowspan="2" class="text-center">支給</th>
          <th class="text-center">基本給</th>
          <th class="text-center">特別手当</th>
          <th class="text-center">交通費</th>
          <th class="text-center">課税支給額</th>
          <th class="text-center">非課税支給額</th>
          <th class="text-center">総支給額</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td class="text-right"><%= number_with_delimiter(@total_pay) %></td>
          <td></td>
          <td class="text-right"><%= number_with_delimiter(@carfare) %></td>
          <td class="text-right"><%= number_with_delimiter(@total_pay) %></td>
          <td class="text-right"><%= number_with_delimiter(@carfare) %></td>
          <% total_pay_wo_tax = @total_pay + @carfare %>
          <td class="text-right"><%= number_with_delimiter(total_pay_wo_tax) %></td>
        </tr>
      </tbody>
      <thead class="thead-light">
        <tr>
          <th rowspan="2" class="text-center">控除</th>
          <th class="text-center">所得税</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td class="text-right"><%= number_with_delimiter(@tax.round(-1)) %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
      <thead class="thead-light">
        <tr>
          <th class="text-center">差引支給額</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-right">
          <% total_pay = total_pay_wo_tax - @tax.round(-1) %>
          <%= number_with_delimiter(total_pay) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>