config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'pdfs/show'

  resources :users
  resources :ranks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :attendance_managements do
    collection do
     get :index_2
     get :show_2
     get :show_3
    end
    member do
      get :edit_2
    end
  end

  namespace :admin do
    resources :attendance_managements, only: [:index, :show, :destroy] do
      collection do
        get :shift
        post :approve
      end
    end
    resources :details
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <%= link_to "勤怠管理アプリ（仮）", root_url, class: 'navbar-brand', id: 'logo' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "ホーム", root_url, class: 'nav-link' %>
        </li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li class="nav-item active dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                管理者機能
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "従業員一覧", users_path, class: "dropdown-item" %>
                <%= link_to "シフト編集", shift_admin_attendance_managements_path, class: "dropdown-item" %>
                <%= link_to "勤怠実績一覧", admin_attendance_managements_path, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
          <li class="nav-item active dropdown">
            <a  class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "プロフィール", current_user, class: "dropdown-item" %>
              <%= link_to "シフト登録", attendance_managements_path, class: "dropdown-item" %>
              <%= link_to "シフト表", index_2_attendance_managements_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
                <%= link_to "ログアウト", logout_path, class: "dropdown-item", method: :delete %>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "ログアウト", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "ログイン", login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">

    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous"> -->

    <title>Attendance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- <%# flash.each do |key, value| %>
      <div class="alert alert-<%#= key %>" role="alert"><%#= value %></div>
    <%# end %> -->
    <!--<a id="skippy" class="sr-only sr-only-focusable" href="#content">
      <div class="container">
        <span class="skiplink-text">Skip to main content</span>
      </div>
    </a>-->
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>